-- Align web schema with desktop SYSCO (JavaFX) field mission tables.

CREATE TABLE field_mission_participants (
    mission_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT pk_field_mission_participants PRIMARY KEY (mission_id, user_id),
    CONSTRAINT fk_fmp_mission FOREIGN KEY (mission_id) REFERENCES field_missions(id) ON DELETE CASCADE,
    CONSTRAINT fk_fmp_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE field_mission_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_id BIGINT NOT NULL,
    file_name VARCHAR(4000) NOT NULL,
    file_path VARCHAR(4000) NOT NULL,
    uploaded_by BIGINT,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_fma_mission FOREIGN KEY (mission_id) REFERENCES field_missions(id) ON DELETE CASCADE,
    CONSTRAINT fk_fma_user FOREIGN KEY (uploaded_by) REFERENCES users(id)
);
