-- SYSCO baseline (H2 / dev). Aligns with javafx-audit-system Oracle schema.sql + courier bootstrap.

CREATE TABLE sous_directions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(512) NOT NULL,
    CONSTRAINT uq_sous_directions_name UNIQUE (name)
);

CREATE TABLE departments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(512) NOT NULL,
    escalation_level1 BIGINT,
    escalation_level2 BIGINT,
    CONSTRAINT uq_departments_name UNIQUE (name)
);

CREATE TABLE directions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(512) NOT NULL,
    sous_direction_id BIGINT,
    CONSTRAINT uq_directions_name UNIQUE (name),
    CONSTRAINT fk_directions_sous FOREIGN KEY (sous_direction_id) REFERENCES sous_directions(id)
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    matricule VARCHAR(255),
    password_hash VARCHAR(255),
    role VARCHAR(64) NOT NULL,
    active INT DEFAULT 1,
    sous_direction_id BIGINT,
    direction_id BIGINT,
    hidden INT DEFAULT 0,
    must_change_password INT DEFAULT 1,
    failed_attempts INT DEFAULT 0,
    lock_until TIMESTAMP,
    email VARCHAR(512),
    attendance_signature VARCHAR(64),
    CONSTRAINT fk_users_sous FOREIGN KEY (sous_direction_id) REFERENCES sous_directions(id),
    CONSTRAINT fk_users_dir FOREIGN KEY (direction_id) REFERENCES directions(id)
);

CREATE TABLE user_permissions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    permission VARCHAR(255),
    CONSTRAINT fk_user_perm_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE tickets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(4000),
    description CLOB,
    priority VARCHAR(64),
    status VARCHAR(64),
    ticket_type VARCHAR(32) NOT NULL,
    department_id BIGINT,
    assigned_to BIGINT,
    created_by BIGINT,
    updated_by BIGINT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ticket_number VARCHAR(128),
    CONSTRAINT fk_tickets_dept FOREIGN KEY (department_id) REFERENCES departments(id),
    CONSTRAINT fk_tickets_assign FOREIGN KEY (assigned_to) REFERENCES users(id),
    CONSTRAINT fk_tickets_creator FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_tickets_updater FOREIGN KEY (updated_by) REFERENCES users(id)
);

CREATE TABLE notifications (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title VARCHAR(512) NOT NULL,
    message CLOB NOT NULL,
    type VARCHAR(128),
    target_type VARCHAR(128),
    target_id BIGINT,
    target_ref VARCHAR(512),
    is_read INT DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notif_user FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE system_audit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255),
    action VARCHAR(255) NOT NULL,
    entity VARCHAR(255),
    entity_id BIGINT,
    details CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE automated_jobs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_title VARCHAR(512) NOT NULL,
    job_description CLOB,
    due_at VARCHAR(64) NOT NULL,
    reminder_minutes INT DEFAULT 60,
    assignee_user_id BIGINT,
    created_by BIGINT,
    recurrence VARCHAR(32) DEFAULT 'ONCE',
    active INT DEFAULT 1,
    last_reminder_at VARCHAR(64),
    last_ticket_created_at VARCHAR(64),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_aj_assignee FOREIGN KEY (assignee_user_id) REFERENCES users(id),
    CONSTRAINT fk_aj_creator FOREIGN KEY (created_by) REFERENCES users(id)
);

CREATE TABLE monthly_reports (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    month_key VARCHAR(32) NOT NULL,
    generated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    file_path VARCHAR(4000),
    total_tickets INT DEFAULT 0,
    open_tickets INT DEFAULT 0,
    in_progress_tickets INT DEFAULT 0,
    closed_tickets INT DEFAULT 0,
    CONSTRAINT uq_monthly_reports_key UNIQUE (month_key)
);

CREATE TABLE datashare_files (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(1024),
    file_path VARCHAR(4000),
    shared_by_id BIGINT,
    shared_by_name VARCHAR(255),
    shared_role VARCHAR(128),
    sous_direction VARCHAR(255),
    date_shared VARCHAR(64),
    time_shared VARCHAR(64),
    expiration_date VARCHAR(64),
    file_size BIGINT DEFAULT 0,
    downloads INT DEFAULT 0
);

CREATE TABLE field_missions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    mission_code VARCHAR(64) NOT NULL,
    title VARCHAR(4000) NOT NULL,
    site_location VARCHAR(4000),
    start_date VARCHAR(32),
    end_date VARCHAR(32),
    description CLOB,
    objectives CLOB,
    status VARCHAR(32) DEFAULT 'PLANNED' NOT NULL,
    report_text CLOB,
    report_submitted_at TIMESTAMP,
    report_author_id BIGINT,
    lead_user_id BIGINT,
    created_by BIGINT NOT NULL,
    order_reference VARCHAR(4000),
    order_issue_date VARCHAR(32),
    order_issued_by VARCHAR(4000),
    order_body CLOB,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_field_missions_code UNIQUE (mission_code),
    CONSTRAINT fk_fm_lead FOREIGN KEY (lead_user_id) REFERENCES users(id),
    CONSTRAINT fk_fm_creator FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_fm_report_author FOREIGN KEY (report_author_id) REFERENCES users(id)
);

CREATE TABLE courier_packets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ref_code VARCHAR(64) NOT NULL UNIQUE,
    title VARCHAR(4000) NOT NULL,
    description CLOB,
    status VARCHAR(32) NOT NULL,
    target_direction_id BIGINT,
    target_sous_direction_id BIGINT,
    created_by BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    assigned_sous_directeur_id BIGINT,
    assigned_inspecteur_id BIGINT,
    assigned_controleur_id BIGINT,
    assigned_verificateur_id BIGINT,
    resolved_at TIMESTAMP,
    resolved_by BIGINT,
    sender VARCHAR(4000),
    priority VARCHAR(32) DEFAULT 'MEDIUM',
    registration_date VARCHAR(32),
    attachment_path VARCHAR(4000),
    secretaire_can_route_sous INT DEFAULT 0 NOT NULL,
    linked_ticket_id BIGINT,
    CONSTRAINT fk_cp_created FOREIGN KEY (created_by) REFERENCES users(id),
    CONSTRAINT fk_cp_tdir FOREIGN KEY (target_direction_id) REFERENCES directions(id),
    CONSTRAINT fk_cp_tsous FOREIGN KEY (target_sous_direction_id) REFERENCES sous_directions(id),
    CONSTRAINT fk_cp_sdir FOREIGN KEY (assigned_sous_directeur_id) REFERENCES users(id),
    CONSTRAINT fk_cp_insp FOREIGN KEY (assigned_inspecteur_id) REFERENCES users(id),
    CONSTRAINT fk_cp_ctrl FOREIGN KEY (assigned_controleur_id) REFERENCES users(id),
    CONSTRAINT fk_cp_ver FOREIGN KEY (assigned_verificateur_id) REFERENCES users(id),
    CONSTRAINT fk_cp_resb FOREIGN KEY (resolved_by) REFERENCES users(id),
    CONSTRAINT fk_cp_ticket FOREIGN KEY (linked_ticket_id) REFERENCES tickets(id)
);

CREATE TABLE courier_journey_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    packet_id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    at_time TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    actor_user_id BIGINT,
    related_user_id BIGINT,
    direction_id BIGINT,
    sous_direction_id BIGINT,
    note CLOB,
    CONSTRAINT fk_cje_p FOREIGN KEY (packet_id) REFERENCES courier_packets(id) ON DELETE CASCADE,
    CONSTRAINT fk_cje_act FOREIGN KEY (actor_user_id) REFERENCES users(id),
    CONSTRAINT fk_cje_rel FOREIGN KEY (related_user_id) REFERENCES users(id)
);

CREATE TABLE courier_packet_extra_directions (
    packet_id BIGINT NOT NULL,
    direction_id BIGINT NOT NULL,
    CONSTRAINT pk_cped PRIMARY KEY (packet_id, direction_id),
    CONSTRAINT fk_cped_p FOREIGN KEY (packet_id) REFERENCES courier_packets(id) ON DELETE CASCADE,
    CONSTRAINT fk_cped_d FOREIGN KEY (direction_id) REFERENCES directions(id)
);

CREATE INDEX idx_ticket_status ON tickets(status);
CREATE INDEX idx_courier_packets_dir ON courier_packets(target_direction_id);
