CREATE TABLE data_share_shared_file (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    file_name VARCHAR(512) NOT NULL,
    shared_by VARCHAR(255) NOT NULL,
    shared_by_role VARCHAR(255),
    recipient_username VARCHAR(255) NOT NULL,
    shared_at TIMESTAMP NOT NULL,
    visible_until TIMESTAMP,
    viewed BOOLEAN NOT NULL DEFAULT FALSE,
    file_path VARCHAR(2048) NOT NULL,
    otp_code VARCHAR(64) NOT NULL
);

CREATE INDEX idx_data_share_recipient ON data_share_shared_file(recipient_username);
CREATE INDEX idx_data_share_sender ON data_share_shared_file(shared_by);
CREATE INDEX idx_data_share_path_sender ON data_share_shared_file(file_path, shared_by);
